### ISSUE TITLE
Updating documents purges attachments.

### ISSUE THREAD

**Issue by RonjaPonja** [rhinoman/couchdb-go#2]
When one .Reads a document into an object, and .Writes the document back into CouchDB with this library the _attachments get purged since one can't add _attachments to the document struct as it would not start with a capital letter and thus not be exposed.
Maybe I am mistaken, but I couldn't figure this out yet. It would be amazing if somebody could point me in some direction. Thanks!

**Comment by RonjaPonja** [comment]
As it usually goes, I found the solution shortly after putting the problem in words :)
One can put something like `json:"_attachments,omitempty"` after a struct member, which tells the json decoder to unpack the _attachments part of the json into this member.
Sorry for the issue ;)

**Comment by rhinoman** [comment]
No problem.
